//
// Copyright (©) 2016 Mobile Academy. All rights reserved.
//

import Foundation

class KinveyClient {

    var kinveyClient = KCSClient.sharedClient()

    func initializeKinvey() {
        kinveyClient.initializeKinveyServiceForAppKey("kid_-J9d_ZSkG-",
                withAppSecret: "25004d30d4994b549870f9d367bc9757",
                usingOptions: nil)
    }

    func registerUserIfNeeded() {
        if KCSUser.activeUser() == nil {
            KCSUser.createAutogeneratedUser(
                [
                    KCSUserAttributeUsername: <#T##username#>,
                    KCSUserAttributeGivenname: <#T##firstname#>,
                    KCSUserAttributeSurname: <#T##lastname#>,
                ],
                completion: { user, errorOrNil, result in
                }
            )
        }
    }
}
